services:

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:8-alpine
    ports:
      - "56379:6379"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "33000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/url_shortener
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
